In [7]:
import numpy as n
p=[1,2,3,4]
r=[x*2 for x in p]
print(r)
narray=n.array([1,2,3,4])
ra=narray*2
print(ra)

[2, 4, 6, 8]
[2 4 6 8]


In [9]:
import numpy as n
a=n.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as n
a=n.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
import  numpy as n
a=n.empty((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
import  numpy as n
a=n.full((2,3),7)
print(a)

[[7 7 7]
 [7 7 7]]


In [21]:
import  numpy as n
a=n.arange(0,10,1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
import  numpy as n
a=n.linspace(0,2,10)
print(a)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [31]:
import  numpy as n
a=n.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
import  numpy as n
a=n.random.rand(2,3)
print(a)

[[0.30016471 0.02053668 0.1551972 ]
 [0.66047097 0.62618525 0.93590107]]


In [39]:
import  numpy as n
a=n.array([1,2,3,4],dtype='float64')
print(a,a.dtype)


[1. 2. 3. 4.] float64


In [43]:
import  numpy as n
a=n.array([[1,2,3],[5,6,7]])
print(a.shape)

(2, 3)


In [47]:
print(a.dtype)

int32


In [57]:
a=n.array([['a','b'],['c','d']])
print(a.shape,a.ndim)
print(a.dtype)

(2, 2) 2
<U1


In [65]:
print(a.size,a.itemsize)
b=n.array(['uday'])
print(b.dtype)

4 4
<U4


In [67]:
a=n.array([1,2,3,4],dtype='int32')
print(a)

[1 2 3 4]


In [81]:
n1=n.array([[1,2,3,4],[5,6,7,8]])
n2=n.array([[3,2,1,4],[6,2,4,8]])
print(n1+n2)
print(n1-n2)
#print(n1*n2)
print(n1//n2)
print(n1%n2)


[[ 4  4  4  8]
 [11  8 11 16]]
[[-2  0  2  0]
 [-1  4  3  0]]
[[0 1 3 1]
 [0 3 1 1]]
[[1 0 0 0]
 [5 0 3 0]]


In [77]:
n1=n.array([['uday'],['aerra']])
n2=n.array([['sai'],['----']])
print(n1+n2)
print(n1-n2)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U5'), dtype('<U4')) -> None

In [99]:
n1=n.array([[1,2,3,4],[5,6,7,8]])
n2=n.array([[3,2,1,4],[6,2,4,8]])
print(n.add(n1,n2))
print(n.subtract(n1,n2))
print(n.multiply(n1,n2))
print(n.divide(n1,n2))
print(n.mod(n1,n2))

[[ 4  4  4  8]
 [11  8 11 16]]
[[-2  0  2  0]
 [-1  4  3  0]]
[[ 3  4  3 16]
 [30 12 28 64]]
[[0.33333333 1.         3.         1.        ]
 [0.83333333 3.         1.75       1.        ]]
[[1 0 0 0]
 [5 0 3 0]]


In [89]:
n1=n.array([['uday'],['aerra']])
n2=n.array([['sai'],['----']])
print(n.add(n1,n2))
print(n.subtract(n1,n2))

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U5'), dtype('<U4')) -> None

In [107]:
n1=n.array([[1,2,3,4],[5,6,7,8]])
n2=n.array([[3,2,1,4],[6,2,4,8]])
n3=n.random.rand(2,4)
print(n3)
print(n.add(n1,n2,n3))
print(n.divide(n1,n2))

[[0.29701507 0.78431783 0.16874719 0.2171993 ]
 [0.30328807 0.17361506 0.72335989 0.34422164]]
[[ 4.  4.  4.  8.]
 [11.  8. 11. 16.]]
[[0.33333333 1.         3.         1.        ]
 [0.83333333 3.         1.75       1.        ]]


In [119]:
print(n2[-1,-1])

8


In [129]:
c=n.array(['u','d','a','y'])
print(c[-1])
print(c[1:-1])
print(c[1:2])
print(c[0:5:1])
print(c[0:5:2])

y
['d' 'a']
['d']
['u' 'd' 'a' 'y']
['u' 'a']


In [136]:
#for i in range(len(c)-1):
for i in range(len(c)):
    print(c[i])

u
d
a
y


In [146]:
a=n.array([1,2,3,4,5,6,7,8])
#index=[0,2,4,6,8](error)
index=[0,2,4,6]
b=a[index]
print(b)

[1 3 5 7]


In [152]:
mask=a>5
print(mask)
newarray=a[mask]
print(newarray)

[False False False False False  True  True  True]
[6 7 8]


In [156]:
arr=n.array(map(int,input()))
print(arr)

 1 2 3 4


In [164]:
a=n.array([1,2,3,4,5,6,7,8])
a[1:4]=[0,0,0]
print(a)

[1 0 0 0 5 6 7 8]


In [4]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5, 6, 7]) 
print(arr[1:5]) 
print(arr[4:]) 
print(arr[:4]) 
print(arr[-3:-1]) 
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.sqrt(arr))
print(np.std(arr))


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
1.707825127659933


In [8]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)


[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
print("vstack:",np.vstack((arr1,arr2)))
print("hstack:",np.hstack((arr1,arr2)))


vstack: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
hstack: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [12]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.ravel(arr))


[1 2 3 4 5 6]


In [14]:
import numpy as np
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])
i = np.where(arr == 30)
print(i)


(array([2], dtype=int64),)


In [16]:
import numpy as np  
arr=np.array([[1,4,2,3],[9,13,61,1],[43,24,88,22]])  
sort_arr=np.sort(arr)  
print(sort_arr)


[[ 1  2  3  4]
 [ 1  9 13 61]
 [22 24 43 88]]
